name: ci

on: push

jobs:
  dialyzer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v1

        with:
          key: dialyzer-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('mix.lock') }}-1

          path: _build

      - uses: actions/setup-elixir@v1

        with:
          elixir-version: ${{ matrix.elixir }}

          otp-version: ${{ matrix.otp }}

      - run: mix deps.get

      - run: mix dialyzer

    strategy:
      matrix:
        elixir: ["1.8.x", "1.9.x", "1.10.x", "1.11.x"]

        exclude:
          - elixir: "1.10.x"

            otp: "20.x"

          - elixir: "1.11.x"

            otp: "20.x"

        otp: [20.x, 21.x, 22.x, 23.x]

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v1

        with:
          key: test-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('mix.lock') }}-1

          path: _build

      - uses: actions/setup-elixir@v1

        with:
          elixir-version: ${{ matrix.elixir }}

          otp-version: ${{ matrix.otp }}

      - run: mix deps.get

      - run: mix test

    strategy:
      matrix:
        elixir: ["1.8.x", "1.9.x", "1.10.x", "1.11.x"]

        exclude:
          - elixir: "1.10.x"

            otp: "20.x"

          - elixir: "1.11.x"

            otp: "20.x"

        otp: [20.x, 21.x, 22.x, 23.x]
